[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
homepage = "https://github.com/zowens/commitlog"
license = "MIT"
name = "commitlog"
readme = "README.md"
repository = "https://github.com/zowens/commitlog"
description = "Sequential, disk-backed commit log library."
version = "0.2.0"
edition = "2021"

[features]
# Enable benchmark of the private api. This flag should be used only
# for benchmarking purposes!
internals = []

[dependencies]
bincode = "1.3.3"
bytes = "1"
chrono = { version = "0.4.38", features = ["serde"] }
crc32c = "0.6"
futures = "0.3.30"
kameo = "0.8.1"
# kameo = { path = "../kameo/crates/kameo" }
log = "0.4.1"
memmap2 = "0.9"
page_size = "0.6"
prost = "0.12"
prost-types = "0.12.6"
rmp-serde = "1.3.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.202", features = ["derive"] }
thiserror = "1.0.61"
tokio = { version = "1.0", features = ["fs", "macros", "rt-multi-thread", "signal"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tonic = "0.11"
twox-hash = "1.6.3"

[build-dependencies]
tonic-build = "0.11"

[dev-dependencies]
criterion = "0.5"
env_logger = "0.11"
rand = "0.8"

[[bench]]
name = "index"
harness = false
required-features = ["internals"]

[[bench]]
name = "stream_index"
harness = false
required-features = ["internals"]

[[bench]]
name = "log_append"
harness = false

[[bench]]
name = "message"
harness = false

[[bench]]
name = "segment"
harness = false
required-features = ["internals"]
